From ea3ca2357018915fb171ee346c81395c50f5c114 Mon Sep 17 00:00:00 2001
From: EmixamPP <dirksen.maxime@gmail.com>
Date: Fri, 15 Jul 2022 21:36:38 +0200
Subject: [PATCH] fix fedora polkit

---
 src/pam.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/pam.py b/src/pam.py
index 08cccef0..ab620a88 100644
--- a/src/pam.py
+++ b/src/pam.py
@@ -41,7 +41,7 @@ def doAuth(pamh):
 	syslog.syslog(syslog.LOG_INFO, "Attempting facial authentication for user " + pamh.get_user())
 
 	# Run compare as python3 subprocess to circumvent python version and import issues
-	status = subprocess.call(["/usr/bin/python3", os.path.dirname(os.path.abspath(__file__)) + "/compare.py", pamh.get_user()])
+	status = subprocess.call(["/usr/bin/python3 " + os.path.dirname(os.path.abspath(__file__)) + "/compare.py " + pamh.get_user() + " &> /dev/null"], shell=True)
 
 	# Status 10 means we couldn't find any face models
 	if status == 10:
